name: ${NAME}
arch: ${ARCH}
version: ${VERSION}
priority: optional
maintainer: Nick Ng <ngyewch@gmail.com>
description: |
  Proxy to allow Prometheus to scrape through NAT etc.
homepage: https://github.com/prometheus-community/PushProx
license: Apache 2.0

contents:
  - src: ${ARCHIVE_DIR}/pushprox-client
    dst: /usr/bin/pushprox-client
    expand: true

  - src: ${ARCHIVE_DIR}/pushprox-proxy
    dst: /usr/bin/pushprox-proxy
    expand: true

  - src: contents
    dst: /
    type: tree

scripts:
  preinstall: scripts/preinstall.sh
  postinstall: scripts/postinstall.sh
  preremove: scripts/preremove.sh
  postremove: scripts/postremove.sh
